language: php
php:
  - 5.5
  - 5.4
  - 5.3
  
before_script:
  - git clone --depth 1 --branch 2.5 git://github.com/cakephp/cakephp ../cakephp && cd ../cakephp
  - mv ../cakephp-meta plugins/Meta
  - chmod -R 777 ../cakephp/app/tmp
  
script:
  - ./lib/Cake/Console/cake test Meta All --stderr
  
notifications:
  - email: false
